### ISSUE TITLE
DVA3221 GPU GTX1650

### ISSUE THREAD

**Issue by Firegamer56** [PeterSuh-Q3/tinycore-redpill#10]
no detection of the gtx1650 board

**Comment by Firegamer56** [comment]
no detection of the gtx1650 board

**Comment by PeterSuh-Q3** [comment]
Is this a GTX1650 using DDR5?
I only provide relevant modules and no environment to support debugging or testing.
(There is no GTX1650.)
I suggest you look at topic DVA3221 in the XPENOLOGY forum for help.
https://xpenology.com/forum/topic/58499-dva3221-loader-development-thread/page/25
