### ISSUE TITLE
virtio gpu sa6400 13500 vgpu not work

### ISSUE THREAD

**Issue by njzydark** [PeterSuh-Q3/tinycore-redpill#12]
I build the loader with pve. It can launch successful, but /dev/dri is empty

**Comment by PeterSuh-Q3** [comment]
It will not work with vgpu.
I think I heard that the successful PVE case was connected by passing through the IGPU. Please refer to the community's success stories.

**Comment by njzydark** [comment]
after add `i915.enable_guc=3` , it work: 

<img width="1368" alt="image" src="https://github.com/PeterSuh-Q3/tinycore-redpill/assets/19601720/71c175a2-babe-4205-a78d-1f6e537f5b6e">

**Comment by PeterSuh-Q3** [comment]
I did it as you suggested, but virtio vgpu was not accelerated.
These are my hardware settings and dmesg results.
I used Intel 4th generation Haswell.

![스크린샷 2023-12-07 오후 1 37 07](https://github.com/PeterSuh-Q3/tinycore-redpill/assets/85427533/3e72373d-ffb4-49eb-9d90-10de460c9d13)

![스크린샷 2023-12-07 오후 1 41 44](https://github.com/PeterSuh-Q3/tinycore-redpill/assets/85427533/c6cac15d-c008-47fa-a453-5734160a79ea)


No settings were added to the two files below.
/etc/modprobe.d/pve-blacklist.conf
/etc/modprobe.d/vfio-pci.conf

I tried adding the settings below to /etc/modules and removing them again.
It's same.
vfio
vfio_iommu_type1
vfio_pci
vfio_virqfd

What's your hardware setting like?
