### ISSUE TITLE
Manually modifying the satamap and rebuild does not take effect

### ISSUE THREAD

**Issue by njzydark** [PeterSuh-Q3/tinycore-redpill#14]
The currently set satamap is not read during build execution

**Comment by PeterSuh-Q3** [comment]
In the case of VM, the preset values in tinycore do not work.
At the Friend boot screen, press the e key within 7 seconds to enter the Edit Sata Line menu and add values directly.

https://github.com/PeterSuh-Q3/tcrpfriend/blob/main/README.md
