### ISSUE TITLE
Select the Extension 

### ISSUE THREAD

**Issue by nemesis122** [PeterSuh-Q3/tinycore-redpill#17]
Hi Peter thank you very much for your work :-)
Small  Question is there a possibilty to select the extension because you already know on a Gen8 the CPU Scaller Extension is not correct working or is this already fixed ?

**Comment by PeterSuh-Q3** [comment]
The only CPU I don't have is Intel 8th generation.
If I had to test it, I'm not sure if my 7th or 9th gen Intel would do the job instead.
Could you please provide proof that the CPU Scaller extension is not working in 8th gen?
dmesg is good, and any capture is good.
