### ISSUE TITLE
Cannot add ext driver

### ISSUE THREAD

**Issue by munchuan** [PeterSuh-Q3/tinycore-redpill#21]
After install, I'm unable to use the network.
Basically I need to add below driver. However, after I ssh in and add it, after installed and rebooted, I still unable to connect to the NAS due to no network driver after it booting into synology.
./rploader.sh ext ds3615xs-7.1.1-42962 add https://github.com/pocopico/redpill-load/raw/master/redpill-misc/rpext-index.json

**Comment by PeterSuh-Q3** [comment]
Now tcrp's ext module management method has changed a lot.
You no longer need to add modules individually.
Like arpl(rr), it uses an integrated module method.
All modules you want are already included, no need to add them separately.

Please write your hardware details in detail in the mshell dedicated topic of the XPENOLOGY forum below and then contact us again.
This issue will be closed.

https://xpenology.com/forum/topic/61839-tinycore-redpill-loader-build-support-tool-m-shell/page/39/
