### ISSUE TITLE
long boot time

### ISSUE THREAD

**Issue by aw0o** [PeterSuh-Q3/tinycore-redpill#25]
Hi,

Thanks for your m-shell, it's very convenient to build a usable loader.

![image](https://github.com/PeterSuh-Q3/tinycore-redpill/assets/56579560/d9344e8f-a1bb-4c68-83bf-d7bc9ed53002)

Everytime when I boot the loader, it stay on this status about 5 minutes and then the "boot timeout exceeded, booting...." appears. Is there any way to make the timeout shorter?

**Comment by PeterSuh-Q3** [comment]
Normally, you should see the "boot timeout exceeded, booting...." message after 7 seconds (at most a few more seconds).

What is happening during the 5 minutes is that the boot process is forcibly stopped with ctrl+c before the 7 second timeout count ends.

You can check the /mnt/tcrp/friendlog.log file.
The cause may be revealed in the log file.

Currently, there is no timestamp in front of the log line, but I will supplement this part again.
