### ISSUE TITLE
Support for DS218+

### ISSUE THREAD

**Issue by antno1000** [PeterSuh-Q3/tinycore-redpill#28]
Can you please add support for DS218+

**Comment by PeterSuh-Q3** [comment]
OK, I'll support DS218+

**Comment by CuriousLad1000** [comment]
Hello, Can you please make a bootable img release so I can use it and test.

**Comment by antno1000** [comment]
@PeterSuh-Q3 Can you please make a img release of the current changes. I would like to try it out.

**Comment by PeterSuh-Q3** [comment]
When you re-enter the mshell loader build menu, it will change to support DS218+ with automatic updates. No need for a new img. However, my testing has not yet confirmed a stable condition.

**Comment by antno1000** [comment]
Hello, I was able to build the loader for DS218+ however, I am unable to get the DSM first setup screen either through the IP address or from finds.synology.com

![image](https://github.com/PeterSuh-Q3/tinycore-redpill/assets/1431318/972e669b-38e8-4af1-b609-782719887323)

**Comment by PeterSuh-Q3** [comment]
As I mentioned above, I have not yet achieved a steady state.
As a result of checking the log coming out through the serial port in the background, 
the kernel panic continues.
There doesn't seem to be a solution right now.

**Comment by antno1000** [comment]
So, for now there's no functional configuration for this model. Can I expect something in the future releases?

**Comment by PeterSuh-Q3** [comment]
Nothing can be guaranteed.

**Comment by PeterSuh-Q3** [comment]
Today I rebuilt lkm for DS218+, which has been missing since mid-March.
I then conducted a DSM installation test and confirmed normal installation as shown below.

![스크린샷 2024-04-11 오후 10 51 06](https://github.com/PeterSuh-Q3/tinycore-redpill/assets/85427533/38a69492-146c-486d-a5a8-34cec5c69d50)

**Comment by antno1000** [comment]
thanks!
