### ISSUE TITLE
server rebooted imediate after selecting grub menu 1

### ISSUE THREAD

**Issue by zfdang** [PeterSuh-Q3/tinycore-redpill#4]
friend entry is ok, but for the first 2 entries, the server reboots immediately...

what could be the problem?

**Comment by PeterSuh-Q3** [comment]
> friend entry is ok, but for the first 2 entries, the server reboots immediately...
> 
> what could be the problem?

Seeing your menu like this one?
If so, this JOT mode does not go through a separate GNU kernel for intermediate processing in the same sense as ARPL's Direct Boot.
JOT is the way it was originally developed and goes straight into synology kernel loading.

![스크린샷 2023-08-26 오후 5 00 40](https://github.com/PeterSuh-Q3/tinycore-redpill/assets/85427533/a89513bf-ef93-4bb5-86c8-6b14c1439316)

**Comment by zfdang** [comment]
I'm able to install 7.2.0 successfully after using clean m-shell image. It works perfectly.
Previously, I just downloaded m-shell scripts with original tcrp image.
