### ISSUE TITLE
[DS3617xs] DSM7.2.2-72806 Crash

### ISSUE THREAD

**Issue by lxh0508** [PeterSuh-Q3/tinycore-redpill#42]
Bootloader: 1.0.4.7
DSM Version: 7.2.2-72806
Platform: Esxi 6.7 U2

Before DSM7.2.2-72803 works fine. I can ping the ip of DSM. But the vm will poweroff automatic while access the DSM via browser

**Comment by PeterSuh-Q3** [comment]
> Bootloader: 1.0.4.7 DSM Version: 7.2.2-72806 Platform: Esxi 6.7 U2
> 
> Before DSM7.2.2-72803 works fine. I can ping the ip of DSM. But the vm will poweroff automatic while access the DSM via browser

This issue has been resolved in a recent patch.
