### ISSUE TITLE
파일 해시값이 맞지 않아 빌드가 되지 않네요.

### ISSUE THREAD

**Issue by jkh0kr** [PeterSuh-Q3/tinycore-redpill#76]
![image](https://github.com/user-attachments/assets/0003143c-b030-4c6e-ad41-37e51d43b104)

빌드할때 해당 버전의 태그파일을 불러와야되는데 마스터 파일을 불러오면서 해시값은 기존 해시값을 들고 있어서 충돌나서 빌드가 되지 않네요.

**Comment by PeterSuh-Q3** [comment]
해당 이슈 수정되었습니다.
